version: '3'

services:
  traefik:
    image: traefik:v2.5
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.middlewares.api-prefix.addprefix.prefix=/"
      - "traefik.http.routers.api.middlewares=api-prefix@docker"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=PathPrefix(`/api/v1`)"
      - "traefik.http.routers.fastapi.entrypoints=http"
      - "traefik.http.routers.fastapi.service=fastapi"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
      - "traefik.http.routers.fastapi.middlewares=api-strip@docker"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api/v1"
